<?php

use Zend\Session\Container;
use Zend\Authentication\AuthenticationService;

$session = new Container('link');
$daterange = $session->offsetGet('daterange');
$auth = new AuthenticationService();
?>
<div class="row">
    <div class="col-xs-12"> 
        <?php
        $rowCount = count($website_data);
        if (isset($message) && $message != '') {
            if ($message == "Link has been successfully Deleted.") {
                ?>
                <div class="alert alert-block alert-danger">
                    <button type="button" class="close" data-dismiss="alert">
                        <i class="icon-remove"></i>
                    </button>

                    <i class="icon-ok red"></i>
        <?php echo $message; ?>

                </div>          
    <?php } else { ?>

                <div class="alert alert-block alert-success">
                    <button type="button" class="close" data-dismiss="alert">
                        <i class="icon-remove"></i>
                    </button>

                    <i class="icon-ok green"></i>
                <?php echo $message; ?>
                </div> 
                <?php
            }
        }
        if (isset($daterange) && !empty($daterange)) {
        ?>    
        <h3 class="header smaller lighter blue current-websiteid" data-id="<?php echo $daterange; ?>">Links</h3>
        <?php }else{ ?>
        <h3 class="header smaller lighter blue current-websiteid" data-id="Select Date Range">Links</h3>
         <?php } ?>

        <div class="row ">

            <div class="well" style="overflow: auto; margin: 0 12px 10px;">

                <div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc">
                    <?php if (isset($daterange) && !empty($daterange)) { ?>
                    <input class="form-control get-date-range hidden" name="date-range-picker" id="date-range-picker" type="text" data-date-format="dd-mm-yyyy" value="<?php echo $daterange; ?>" />
                    <?php }else{ ?>
                    <input class="form-control get-date-range hidden" name="date-range-picker" id="date-range-picker" type="text" data-date-format="dd-mm-yyyy" />
                    <?php } ?>                  
                    <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                    <span></span> <b class="caret"></b>
                </div>
                            <div class="pull-left">

                <select class="form-control" id="form-field-select-1" data-id="link" style="width: 300px; margin-right: 15px; margin-top: 5px;">
                    <?php if (isset($current_website_id) && $current_website_id != '') { ?>
                        <?php
                        foreach ($client_websites as $website) {
                            if ($current_website_id == $website->id) {
                                ?>
                                <option value="<?php echo $website->id ?>"><?php echo $website->website ?></option>
                            <?php
                            }
                        }
                        ?>
                        <?php
                        foreach ($client_websites as $website) {
                            if ($current_website_id != $website->id) {
                                ?>                        
                                <option value="<?php echo $website->id ?>"><?php echo $website->website ?></option>
                            <?php
                            }
                        }
                        ?>
                    <?php } else { ?>

                        <?php foreach ($client_websites as $website) {
                            ?>
                            <option value="<?php echo $website->id ?>"><?php echo $website->website ?></option>                       
                    <?php }}
                    ?>
                </select>

            </div>
                <?php if ($auth->getIdentity()->roles_id == 3) {
                ?>

                <?php
            } else if ($auth->getIdentity()->roles_id == 2) {
                if ($applying_user_rights->crud_link == 1) {
                    ?>
                 <div class="pull-left" style="margin-left: 15px">                
                    <a href="/link/add/<?php echo $current_website_id; ?>" id="addbuttonlink" class="btn btn-primary">Add New Link</a>
                </div>   
                <div class="pull-left" style="margin-left: 15px">
                     <?php if($rowCount > 0){
                         ?>
                    <a href="#" class="btn btn-danger pull-right multiple-delete" data-id="link">Delete Selected Links</a>
                     <?php } ?>
                </div>   
                <div class="pull-left" style="margin-left: 15px">
                    <?php
                        $num = 0;
                        foreach ($website_data as $transcriptt) {
                            $session->offsetSet('leadobject' . $num, $transcriptt);
                            $num = $num + 1;
                        }
                       if($rowCount > 0){
                         ?>
                    <a href="/link/exportdata/<?php echo $num - 1; ?>" class="btn btn-grey pull-right" data-id="link" style="margin-right: 10px;">Export</a>
                       <?php } ?>
                </div> 
                <?php
                } else {
                    
                }
            } else {
                ?>   
                <div class="pull-left" style="margin-left: 15px">
             
                   <a href="/link/add/<?php echo $current_website_id; ?>" id="addbuttonlink" class="btn btn-primary">Add New Link</a>
                </div>   
                <div class="pull-left" style="margin-left: 15px">
                     <?php if($rowCount > 0){
                         ?>
                    <a href="#" class="btn btn-danger pull-right multiple-delete" data-id="link">Delete Selected Links</a>
                     <?php } ?>
                </div>   
                <div class="pull-left" style="margin-left: 15px">
                    <?php
                        $num = 0;
                        foreach ($website_data as $transcriptt) {
                            $session->offsetSet('leadobject' . $num, $transcriptt);
                            $num = $num + 1;
                        }
                       if($rowCount > 0){
                         ?>
                    <a href="/link/exportdata/<?php echo $num - 1; ?>" class="btn btn-grey pull-right" data-id="link" style="margin-right: 10px;">Export</a>
                       <?php } ?>
                </div> 
                <?php
            }
            ?>
  
            </div>

        </div>    
        <?php 
       if ($rowCount > 0) { ?>
        <div class="table-header" style="min-height: 42px;">       

            Results for "Links"
           
        </div>
       
        <div class="table-responsive">
            <table id="sample-table-2" class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="center">
                            <label>
                                <input type="checkbox" class="ace" data-id="all" />
                                <span class="lbl"></span>
                            </label>
                        </th>
                        <th>Date</th>
                        <th>URL</th>                    

                        <th class="hidden"></th>
                        <th class="hidden"></th>
                        <th class="hidden"></th>
                        <th class="hidden"></th>
                        <th class="hidden"></th>
                       
                        
                        <?php if ($auth->getIdentity()->roles_id == 3) {
                             ?>   <th class="hidden"></th> <?php
                        }else if($auth->getIdentity()->roles_id == 2) {
                                if ($applying_user_rights->crud_link == 1) {
                                  ?>   
                            <th>Actions</th>
                            <?php  
                                }else{
                                   ?>   <th class="hidden"></th> <?php
                                }
                        }else {
                            ?>   
                            <th>Actions</th>
                            <?php
                        }
                        ?>
                    </tr>
                </thead>

                <tbody class="linktable">
                    <tr>
                        <?php
                         
                        foreach ($website_data as $link) {
                            ?>
                            <td class="center">
                                <label>
                                    <input type="checkbox" class="ace" data-id="<?php echo $link->id; ?>" />
                                    <span class="lbl"></span>
                                </label>
                            </td>

                            <td>
                           <?php echo $link->date; ?>
                            </td>
                            <td><?php echo $link->url; ?></td>



                            <td class="hidden"></td>
                            <td class="hidden"></td>
                            <td class="hidden"></td>
                            <td class="hidden"></td>
                            <td class="hidden"></td>
                            
                           
                       
                            <?php if ($auth->getIdentity()->roles_id == 3) {
                                ?>  <td class="hidden"></td> <?php
                            } else if($auth->getIdentity()->roles_id == 2) {
                                if ($applying_user_rights->crud_link == 1) {
                                            ?>
                                <td>
                                    <div class="visible-md visible-lg hidden-sm hidden-xs action-buttons">

                                        <a class="green" href="<?php echo $this->url('link', array('action' => 'edit', 'id' => $link->id)); ?>">
                                            <i class="icon-pencil bigger-130"></i>
                                        </a>
                                        <!--<a href="<?php //echo $this->url('clients', array('action' => 'dialoge', 'id' => $client->id));    ?>" class="tooltip-error" data-rel="tooltip" title="Dialoge">-->
                                        <a href="#" role="button" class="red" onclick="deleterow(<?php echo $link->id; ?>, 'link');"> 
                                            <i class="icon-trash bigger-130"></i>
                                        </a>
                                       
                                    </div>
                                </td>    
                                
                                <?php }else{
                                           ?>  <td class="hidden"></td> <?php 
                                        }
                            }else{ ?>   
                                <td>
                                    <div class="visible-md visible-lg hidden-sm hidden-xs action-buttons">

                                        <a class="green" href="<?php echo $this->url('link', array('action' => 'edit', 'id' => $link->id)); ?>">
                                            <i class="icon-pencil bigger-130"></i>
                                        </a>
                                        <!--<a href="<?php //echo $this->url('clients', array('action' => 'dialoge', 'id' => $client->id));    ?>" class="tooltip-error" data-rel="tooltip" title="Dialoge">-->
                                        <a href="#" role="button" class="red" onclick="deleterow(<?php echo $link->id; ?>, 'link');"> 
                                            <i class="icon-trash bigger-130"></i>
                                        </a>
                                       
                                    </div>

                                    <div class="visible-xs visible-sm hidden-md hidden-lg">
                                        <div class="inline position-relative">
                                            <button class="btn btn-minier btn-yellow dropdown-toggle" data-toggle="dropdown">
                                                <i class="icon-caret-down icon-only bigger-120"></i>
                                            </button>

                                            <ul class="dropdown-menu dropdown-only-icon dropdown-yellow pull-right dropdown-caret dropdown-close">

                                                <li>
                                                    <a href="<?php echo $this->url('link', array('action' => 'edit', 'id' => $link->id)); ?>" class="tooltip-success" data-rel="tooltip" title="Edit">
                                                        <span class="green">
                                                            <i class="icon-edit bigger-120"></i>
                                                        </span>
                                                    </a>
                                                </li>

                                                <li>
                                                    <a href="<?php echo $this->url('clients', array('action' => 'delete', 'id' => $client->id)); ?>" class="tooltip-error" data-rel="tooltip" title="Delete">
                                                        <span class="red">
                                                            <i class="icon-trash bigger-120"></i>
                                                        </span>
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </td>
                            <?php
                        }
                        ?>
                        </tr>
                <?php } ?>              
                </tbody>
            </table>
        </div>
        <?php }else{
            echo "NO RESULT FOUND";
        } ?> 
    </div>
</div>
<div id="modal-table" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header no-padding">
                <div class="table-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        <span class="white">&times;</span>
                    </button>
                    Delete Link
                </div>
            </div>

            <div class="modal-body no-padding">
                <h4 style="margin: 20px 3px;">Are you sure you want to delete ?</h4>
            </div>

            <div class="modal-footer no-margin-top">

                <button class="btn btn-sm btn-danger pull-left delete_user_btn" data-dismiss="modal">
                    <i class="icon-remove"></i>
                    Yes
                </button>

                <button class="btn btn-sm btn-primary pull-left" data-dismiss="modal">
                    <i class="icon-only"></i>
                    Close
                </button>

            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal-table -->
<?php
$message = '';
$session->offsetSet('current_website_id', '');
$session->offsetSet('daterange', '');
$session->offsetSet('from', '');
$session->offsetSet('till', '');
$session->offsetSet('msg', '');
?>
<!--<h4 class="pink">
        <i class="icon-hand-right green"></i>
        <a href="#modal-form" role="button" class="blue" data-toggle="modal" onclick="getHolidayModal('GET', 'add',<?php echo $current_website_id; ?>);" > Form Inside a Modal Box </a>
</h4>
<div id="modal-form" class="modal" tabindex="-1">
        <div class="modal-dialog">
                <div class="modal-content">
                        <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="blue bigger">Please fill the following form fields</h4>
                        </div>

                        <div class="modal-body overflow-visible">
                                <div class="row">
                                        <div class="col-xs-12 col-sm-5">
                                                <div class="space"></div>

                                                <input type="file" />
                                        </div>

                                        <div class="col-xs-12 col-sm-7">
                                                <div class="form-group">
                                                        <label for="form-field-select-3">Location</label>

                                                        <div>
                                                                <select class="chosen-select" data-placeholder="Choose a Country...">
                                                                        <option value="">&nbsp;</option>
                                                                        <option value="AL">Alabama</option>
                                                                        <option value="AK">Alaska</option>
                                                                        <option value="AZ">Arizona</option>
                                                                        <option value="AR">Arkansas</option>
                                                                        <option value="CA">California</option>
                                                                        <option value="CO">Colorado</option>
                                                                        <option value="CT">Connecticut</option>
                                                                        <option value="DE">Delaware</option>
                                                                        <option value="FL">Florida</option>
                                                                        <option value="GA">Georgia</option>
                                                                        <option value="HI">Hawaii</option>
                                                                        <option value="ID">Idaho</option>
                                                                        <option value="IL">Illinois</option>
                                                                        <option value="IN">Indiana</option>
                                                                        <option value="IA">Iowa</option>
                                                                        <option value="KS">Kansas</option>
                                                                        <option value="KY">Kentucky</option>
                                                                        <option value="LA">Louisiana</option>
                                                                        <option value="ME">Maine</option>
                                                                        <option value="MD">Maryland</option>
                                                                        <option value="MA">Massachusetts</option>
                                                                        <option value="MI">Michigan</option>
                                                                        <option value="MN">Minnesota</option>
                                                                        <option value="MS">Mississippi</option>
                                                                        <option value="MO">Missouri</option>
                                                                        <option value="MT">Montana</option>
                                                                        <option value="NE">Nebraska</option>
                                                                        <option value="NV">Nevada</option>
                                                                        <option value="NH">New Hampshire</option>
                                                                        <option value="NJ">New Jersey</option>
                                                                        <option value="NM">New Mexico</option>
                                                                        <option value="NY">New York</option>
                                                                        <option value="NC">North Carolina</option>
                                                                        <option value="ND">North Dakota</option>
                                                                        <option value="OH">Ohio</option>
                                                                        <option value="OK">Oklahoma</option>
                                                                        <option value="OR">Oregon</option>
                                                                        <option value="PA">Pennsylvania</option>
                                                                        <option value="RI">Rhode Island</option>
                                                                        <option value="SC">South Carolina</option>
                                                                        <option value="SD">South Dakota</option>
                                                                        <option value="TN">Tennessee</option>
                                                                        <option value="TX">Texas</option>
                                                                        <option value="UT">Utah</option>
                                                                        <option value="VT">Vermont</option>
                                                                        <option value="VA">Virginia</option>
                                                                        <option value="WA">Washington</option>
                                                                        <option value="WV">West Virginia</option>
                                                                        <option value="WI">Wisconsin</option>
                                                                        <option value="WY">Wyoming</option>
                                                                </select>
                                                        </div>
                                                </div>

                                                <div class="space-4"></div>

                                                <div class="form-group">
                                                        <label for="form-field-username">Username</label>

                                                        <div>
                                                                <input class="input-large" type="text" id="form-field-username" placeholder="Username" value="alexdoe" />
                                                        </div>
                                                </div>

                                                <div class="space-4"></div>

                                                <div class="form-group">
                                                        <label for="form-field-first">Name</label>

                                                        <div>
                                                                <input class="input-medium" type="text" id="form-field-first" placeholder="First Name" value="Alex" />
                                                                <input class="input-medium" type="text" id="form-field-last" placeholder="Last Name" value="Doe" />
                                                        </div>
                                                </div>
                                        </div>
                                </div>
                        </div>

                        <div class="modal-footer">
                                <button class="btn btn-sm" data-dismiss="modal">
                                        <i class="icon-remove"></i>
                                        Cancel
                                </button>

                                <button class="btn btn-sm btn-primary">
                                        <i class="icon-ok"></i>
                                        Save
                                </button>
                        </div>
                </div>
        </div>
</div> PAGE CONTENT ENDS -->