<?php

use Zend\Session\Container;

$session = new Container('lead');
$daterange = $session->offsetGet('daterange');
//print_r($daterange);exit;
use Zend\Authentication\AuthenticationService;

$auth = new AuthenticationService();
?>
<div class="row">
    <div class="col-xs-12"> 
        <?php
        $rowCount = count($website_data);

//         print_r($website_data);exit;
        if (isset($message) && $message != '') {
            if ($message == "Lead has been successfully Deleted.") {
                ?>
                <div class="alert alert-block alert-danger">
                    <button type="button" class="close" data-dismiss="alert">
                        <i class="icon-remove"></i>
                    </button>

                    <i class="icon-ok red"></i>
        <?php echo $message; ?>

                </div>          
    <?php } else { ?>

                <div class="alert alert-block alert-success">
                    <button type="button" class="close" data-dismiss="alert">
                        <i class="icon-remove"></i>
                    </button>

                    <i class="icon-ok green"></i>
                <?php echo $message; ?>
                </div> 
                <?php
            }
        }
        if (isset($daterange) && !empty($daterange)) {
        ?>    
        <h3 class="header smaller lighter blue current-websiteid" data-id="<?php echo $daterange; ?>">Leads</h3>        
        <?php }else{ ?>
         <h3 class="header smaller lighter blue current-websiteid" data-id="Select Date Range">Leads</h3>
        <?php } ?>
        <div class="row ">

            <div class="well" style="overflow: auto; margin: 0 12px 10px;">

                <div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc">
                    <?php if (isset($daterange) && !empty($daterange)) { ?>
                    <input class="form-control get-date-range hidden" name="date-range-picker" id="date-range-picker" type="text" data-date-format="dd-mm-yyyy" value="<?php echo $daterange; ?>" />
                    <?php }else{ ?>
                    <input class="form-control get-date-range hidden" name="date-range-picker" id="date-range-picker" type="text" data-date-format="dd-mm-yyyy" />
                    <?php } ?>
                    <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>                    
                    <span></span>     <b class="caret"></b>
                </div>
                <div class="pull-left">

                    <select class="form-control" id="form-field-select-1" data-id="lead" style="width: 300px; margin-right: 15px; margin-top: 5px;">
                        <?php if (isset($current_website_id) && $current_website_id != '') { ?>
                            <?php
                            foreach ($client_websites as $website) {
                                if ($current_website_id == $website->id) {
                                    ?>
                                    <option value="<?php echo $website->id ?>"><?php echo $website->website ?></option>
                                <?php
                                }
                            }
                            ?>
                            <?php
                            foreach ($client_websites as $website) {
                                if ($current_website_id != $website->id) {
                                    ?>                        
                                    <option value="<?php echo $website->id ?>"><?php echo $website->website ?></option>
                                <?php
                                }
                            }
                            ?>
                        <?php } else { ?>

                            <?php foreach ($client_websites as $website) {
                                ?>
                                <option value="<?php echo $website->id ?>"><?php echo $website->website ?></option>
                            <?php } ?>
                        <?php }
                        ?>
                    </select>

                </div> 
                <?php if ($auth->getIdentity()->roles_id == 3) {
                    ?>

                    <?php
                } else if ($auth->getIdentity()->roles_id == 2) {
                    if ($applying_user_rights->crud_lead == 1) {
                        ?>
                                        <!--<div class="pull-left" style="margin-left: 15px">-->
                                           <a href="/lead/add/<?php echo $current_website_id; ?>" id="addbuttonlink" ></a>
                                        <!--</div>-->   
                        <div class="pull-left" style="margin-left: 15px">
                            <?php if ($rowCount > 0) {
                                ?>
                                <a href="#" class="btn btn-danger pull-right multiple-delete" data-id="lead">Delete Selected Leads</a>
                            <?php } ?>
                        </div>   
                        <div class="pull-left" style="margin-left: 15px">
                            <?php
                            $num = 0;
                            foreach ($website_data as $leadd) {
                                $session->offsetSet('leadobject' . $num, $leadd);
                                $num = $num + 1;
                            }
                            if ($rowCount > 0) {
                                ?>
                                <a href="/lead/exportdata/<?php echo $num - 1; ?>" class="btn btn-grey pull-right" data-id="transcript" style="margin-right: 10px;">Export</a>
                        <?php } ?>
                        </div> 
                        <?php
                    } else {
                        
                    }
                } else {
                    ?>
                                         <a href="/lead/add/<?php echo $current_website_id; ?>" id="addbuttonlink" ></a>
<!--                                    <div class="pull-left" style="margin-left: 15px">
                       <a href="/lead/add/<?php //echo $current_website_id; ?>" id="addbuttonlink" class="btn btn-primary">Add New Lead</a>
                    </div>   -->
                    <div class="pull-left" style="margin-left: 15px">
                        <?php if ($rowCount > 0) {
                            ?>
                            <a href="#" class="btn btn-danger pull-right multiple-delete" data-id="lead">Delete Selected Leads</a>
                        <?php } ?>
                    </div>   
                    <div class="pull-left" style="margin-left: 15px">
                        <?php
                        $num = 0;
                        foreach ($website_data as $leadd) {
                            $session->offsetSet('leadobject' . $num, $leadd);
                            $num = $num + 1;
                        }
                        if ($rowCount > 0) {
                            ?>
                            <a href="/lead/exportdata/<?php echo $num - 1; ?>" class="btn btn-grey pull-right" data-id="transcript" style="margin-right: 10px;">Export</a>
                    <?php } ?>
                    </div> 
    <?php
}
?>  

            </div>             
        </div>    
         <?php if ($rowCount > 0) { ?>
        <div class="table-header" style="min-height: 42px;">           
 Results for "Leads"

        </div>

        <div class="table-responsive">
            <table id="sample-table-2" class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="center">
                            <label>
                                <input type="checkbox" class="ace" data-id="all" />
                                <span class="lbl"></span>
                            </label>
                        </th>  
                        <th>Caller Type</th>     
                        <th>Lead Date</th>
                        <th>Lead Source</th>                           
                        <th>Incomming Ph</th>
                        <th>Call Duration</th>
                        <th>Leads Name</th>
                        <th>Leads email</th>

                        <?php if ($auth->getIdentity()->roles_id == 3) {
                            ?>   <th class="hidden"></th> <?php
                    } else if ($auth->getIdentity()->roles_id == 2) {
                        if ($applying_user_rights->crud_lead == 1) {
                                ?>   
                                <th>Actions</th>
                                    <?php
                                } else {
                                    ?>   <th class="hidden"></th> <?php
                        }
                    } else {
                                ?>   
                            <th>Actions</th>
                    <?php
                }
                ?>
                    </tr>
                </thead>

                <tbody class="leadtable">
                    <tr>

                        <?php
//                         print_r($website_data);
                        foreach ($website_data as $lead) {
                            ?>
                            <td class="center">
                                <label>
                                    <input type="checkbox" class="ace" data-id="<?php echo $lead->id; ?>" />
                                    <span class="lbl"></span>
                                </label>
                            </td>
                            <td><?php
                                if ($lead->caller_type == 1) {
                                    echo "Poten Newclient";
                                } else if ($lead->caller_type == 2) {
                                    echo "Non-Client";
                                } else if ($lead->caller_type == 3) {
                                    echo "Soliciter";
                                } else if ($lead->caller_type == 4) {
                                    echo "Current Client";
                                } else if ($lead->caller_type == 5) {
                                    echo "Repeated";
                                } else if ($lead->caller_type == 6) {
                                    echo "Web Form";
                                } else if ($lead->caller_type == 7) {
                                    echo "Test call";
                                } else if ($lead->caller_type == 7) {
                                    echo "No Recording";                                
                                } else {
                                    echo " ";
                                }
                                ?></td>
                            <td><?php 
                            $originalDate = $lead->lead_date;
                            $newDate = date("m-d-Y", strtotime($originalDate));
                            echo $newDate;  
                            
                            
                            ?></td>
                            <td><?php
                            if ($lead->lead_source == 1) {
                                echo "Phone Call";
                            } else if ($lead->lead_source == 2) {
                                echo "Contact Form";
                            } else {
                                echo "Book Download";
                            }
                                ?></td>
                            <td><?php echo $lead->inc_phone; ?></td>
                            <td><?php echo $lead->call_duration; ?></td>
                            <td><?php echo $lead->lead_name; ?></td>
                            <td><?php echo $lead->lead_email; ?></td>

                        <?php if ($auth->getIdentity()->roles_id == 3) {
                            ?>  <td class="hidden"></td> <?php
                        } else if ($auth->getIdentity()->roles_id == 2) {
                            if ($applying_user_rights->crud_lead == 1) {
                                ?>
                                    <td>
                                        <div class="visible-md visible-lg hidden-sm hidden-xs action-buttons">
                                            <a class="green" href="<?php echo $this->url('lead', array('action' => 'edit', 'id' => $lead->id)); ?>">
                                                <i class="icon-pencil bigger-130"></i>
                                            </a>
                                            <!--<a href="<?php //echo $this->url('clients', array('action' => 'dialoge', 'id' => $client->id));    ?>" class="tooltip-error" data-rel="tooltip" title="Dialoge">-->
                                            <a href="#" role="button" class="red" onclick="deleterow(<?php echo $lead->id; ?>, 'lead');"> 
                                                <i class="icon-trash bigger-130"></i>
                                            </a>
                                        </div>
                                    </td>    

                                <?php } else {
                                    ?>  <td class="hidden"></td> <?php
                                }
                            } else {
                                ?>   
                                <td>
                                    <div class="visible-md visible-lg hidden-sm hidden-xs action-buttons">
                                        <a class="green" href="<?php echo $this->url('lead', array('action' => 'edit', 'id' => $lead->id)); ?>">
                                            <i class="icon-pencil bigger-130"></i>
                                        </a>
                                        <!--<a href="<?php //echo $this->url('clients', array('action' => 'dialoge', 'id' => $client->id));    ?>" class="tooltip-error" data-rel="tooltip" title="Dialoge">-->
                                        <a href="#" role="button" class="red" onclick="deleterow(<?php echo $lead->id; ?>, 'lead');"> 
                                            <i class="icon-trash bigger-130"></i>
                                        </a>
                                    </div>

                                    <div class="visible-xs visible-sm hidden-md hidden-lg">
                                        <div class="inline position-relative">
                                            <button class="btn btn-minier btn-yellow dropdown-toggle" data-toggle="dropdown">
                                                <i class="icon-caret-down icon-only bigger-120"></i>
                                            </button>

                                            <ul class="dropdown-menu dropdown-only-icon dropdown-yellow pull-right dropdown-caret dropdown-close">

                                                <li>
                                                    <a href="<?php echo $this->url('lead', array('action' => 'edit', 'id' => $lead->id)); ?>" class="tooltip-success" data-rel="tooltip" title="Edit">
                                                        <span class="green">
                                                            <i class="icon-edit bigger-120"></i>
                                                        </span>
                                                    </a>
                                                </li>

                                                <li>
                                                    <a href="<?php echo $this->url('clients', array('action' => 'delete', 'id' => $client->id)); ?>" class="tooltip-error" data-rel="tooltip" title="Delete">
                                                        <span class="red">
                                                            <i class="icon-trash bigger-120"></i>
                                                        </span>
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </td>
                            <?php
                        }
                        ?>                               
                        </tr>
                        <?php } ?>              
                </tbody>
            </table>
        </div>
        <?php }else{
            echo "NO RESULT FOUND";
        } ?> 
    </div>
</div>
<div id="modal-table" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header no-padding">
                <div class="table-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        <span class="white">&times;</span>
                    </button>
                    Delete Lead
                </div>
            </div>

            <div class="modal-body no-padding">
                <h4 style="margin: 20px 3px;">Are you sure you want to delete ?</h4>
            </div>

            <div class="modal-footer no-margin-top">

                <button class="btn btn-sm btn-danger pull-left delete_user_btn" data-dismiss="modal">
                    <i class="icon-remove"></i>
                    Yes
                </button>

                <button class="btn btn-sm btn-primary pull-left" data-dismiss="modal">
                    <i class="icon-only"></i>
                    Close
                </button>

            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal-table -->
<?php
$message = '';
$session->offsetSet('current_website_id', '');
$session->offsetSet('daterange', '');
$session->offsetSet('from', '');
$session->offsetSet('till', '');
$session->offsetSet('msg', '');
?>
