<?php

use Zend\Session\Container;

$session = new Container('lead');
$daterange=$session->offsetGet('daterange');
?>
<div class="row">
    <div class="col-xs-12"> 
        <?php
//         print_r($website_data);exit;
        if (isset($message) && $message != '') {
            if ($message == "Lead has been successfully Deleted.") {
                ?>
                <div class="alert alert-block alert-danger">
                    <button type="button" class="close" data-dismiss="alert">
                        <i class="icon-remove"></i>
                    </button>

                    <i class="icon-ok red"></i>
                    <?php echo $message; ?>

                </div>          
            <?php } else { ?>

                <div class="alert alert-block alert-success">
                    <button type="button" class="close" data-dismiss="alert">
                        <i class="icon-remove"></i>
                    </button>

                    <i class="icon-ok green"></i>
                    <?php echo $message; ?>
                </div> 
            <?php
            }
        }
        ?>    
        <h3 class="header smaller lighter blue current-websiteid" data-id="">Leads</h3>
        
        <div class="row ">
           
            <div class="well" style="overflow: auto">

               <div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc">
                 <input class="form-control get-date-range hidden" name="date-range-picker" id="date-range-picker" type="text" data-date-format="dd-mm-yyyy" />
                   <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                   <span></span> <b class="caret"></b>
               </div>
            </div>             
        </div>    
        <div class="table-header">
            <a href="/lead/add/<?php echo $current_website_id; ?>" id="addbuttonlink" class="btn btn-primary">Add New Lead</a>
            <a href="#" class="btn btn-danger pull-right multiple-delete" data-id="lead">Delete Selected Leads</a>
            <div class="pull-right">

                <select class="form-control" id="form-field-select-1" data-id="lead" style="width: 300px; margin-right: 15px; margin-top: 5px;">
                    <?php if (isset($current_website_id) && $current_website_id != '') { ?>
                        <?php
                        foreach ($client_websites as $website) {
                            if ($current_website_id == $website->id) {
                                ?>
                                <option value="<?php echo $website->id ?>"><?php echo $website->website ?></option>
                            <?php }
                        }
                        ?>
                        <?php
                        foreach ($client_websites as $website) {
                            if ($current_website_id != $website->id) {
                                ?>                        
                                <option value="<?php echo $website->id ?>"><?php echo $website->website ?></option>
                            <?php }
                        }
                        ?>
                    <?php } else { ?>

                        <?php foreach ($client_websites as $website) {
                            ?>
                            <option value="<?php echo $website->id ?>"><?php echo $website->website ?></option>
                        <?php } ?>
                    <?php }
                    ?>
                </select>

            </div>

        </div>

        <div class="table-responsive">
            <table id="sample-table-2" class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="center">
                            <label>
                                <input type="checkbox" class="ace" data-id="all" />
                                <span class="lbl"></span>
                            </label>
                        </th>  
                        <th>Caller Type</th>     
                        <th>Lead Date</th>
                        <th>Lead Source</th>                           
                        <th>Incomming Ph</th>
                        <th>Call Duration</th>
                        <th>Leads Name</th>
                        <th>Leads email</th>
                        <th>Actions</th>
                    </tr>
                </thead>

                <tbody class="leadtable">
                    <tr>

                        <?php
//                         print_r($website_data);
                        foreach ($website_data as $lead) {                         
                            ?>
                            <td class="center">
                                <label>
                                    <input type="checkbox" class="ace" data-id="<?php echo $lead->id; ?>" />
                                    <span class="lbl"></span>
                                </label>
                            </td>
                            <td><?php echo $lead->caller_type; ?></td>
                            <td><?php echo $lead->lead_date; ?></td>
                            <td><?php echo $lead->lead_source; ?></td>
                            <td><?php echo $lead->inc_phone; ?></td>
                            <td><?php echo $lead->call_duration; ?></td>
                            <td><?php echo $lead->lead_name; ?></td>
                            <td><?php echo $lead->lead_email; ?></td>

                            <td>
                                <div class="visible-md visible-lg hidden-sm hidden-xs action-buttons">
                                    <a class="blue" href="#">
                                        <i class="icon-zoom-in bigger-130"></i>
                                    </a>

                                    <a class="green" href="<?php echo $this->url('lead', array('action' => 'edit', 'id' => $lead->id)); ?>">
                                        <i class="icon-pencil bigger-130"></i>
                                    </a>
                                    <!--<a href="<?php //echo $this->url('clients', array('action' => 'dialoge', 'id' => $client->id));   ?>" class="tooltip-error" data-rel="tooltip" title="Dialoge">-->
                                    <a href="#" role="button" class="red" onclick="deleterow(<?php echo $lead->id; ?>,'lead');"> 
                                        <i class="icon-trash bigger-130"></i>
                                    </a>
                                </div>

                                <div class="visible-xs visible-sm hidden-md hidden-lg">
                                    <div class="inline position-relative">
                                        <button class="btn btn-minier btn-yellow dropdown-toggle" data-toggle="dropdown">
                                            <i class="icon-caret-down icon-only bigger-120"></i>
                                        </button>

                                        <ul class="dropdown-menu dropdown-only-icon dropdown-yellow pull-right dropdown-caret dropdown-close">
                                            <li>
                                                <a href="#" class="tooltip-info" data-rel="tooltip" title="View">
                                                    <span class="blue">
                                                        <i class="icon-zoom-in bigger-120"></i>
                                                    </span>
                                                </a>
                                            </li>

                                            <li>
                                                <a href="<?php echo $this->url('lead', array('action' => 'edit', 'id' => $lead->id)); ?>" class="tooltip-success" data-rel="tooltip" title="Edit">
                                                    <span class="green">
                                                        <i class="icon-edit bigger-120"></i>
                                                    </span>
                                                </a>
                                            </li>

                                            <li>
                                                <a href="<?php echo $this->url('clients', array('action' => 'delete', 'id' => $client->id)); ?>" class="tooltip-error" data-rel="tooltip" title="Delete">
                                                    <span class="red">
                                                        <i class="icon-trash bigger-120"></i>
                                                    </span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </td>
                        </tr>
                  <?php } ?>              
                </tbody>
            </table>
        </div>
    </div>
</div>
<div id="modal-table" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header no-padding">
                <div class="table-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        <span class="white">&times;</span>
                    </button>
                    Delete Lead
                </div>
            </div>

            <div class="modal-body no-padding">
                <h4 style="margin: 20px 3px;">Are you sure you want to delete ?</h4>
            </div>

            <div class="modal-footer no-margin-top">

                <button class="btn btn-sm btn-danger pull-left delete_user_btn" data-dismiss="modal">
                    <i class="icon-remove"></i>
                    Yes
                </button>

                <button class="btn btn-sm btn-primary pull-left" data-dismiss="modal">
                    <i class="icon-only"></i>
                    Close
                </button>

            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal-table -->
<?php
$message = '';
$session->offsetSet('current_website_id', '');
$session->offsetSet('from', '');
$session->offsetSet('till', '');
$session->offsetSet('msg', '');
?>
