<?php

use Zend\Session\Container;
use Zend\Authentication\AuthenticationService;

$session = new Container('googleapi');
$daterange = $session->offsetGet('daterange');
$auth = new AuthenticationService();
?>
<div class="row">
    <div class="col-xs-12"> 
        <?php
//        echo "asdada";
//         print_r($website_data);
        if (isset($message) && $message != '') {
            if ($message == "Website Traffic has been successfully Deleted.") {
                ?>
                <div class="alert alert-block alert-danger">
                    <button type="button" class="close" data-dismiss="alert">
                        <i class="icon-remove"></i>
                    </button>

                    <i class="icon-ok red"></i>
        <?php echo $message; ?>

                </div>          
    <?php } else { ?>

                <div class="alert alert-block alert-success">
                    <button type="button" class="close" data-dismiss="alert">
                        <i class="icon-remove"></i>
                    </button>

                    <i class="icon-ok green"></i>
                <?php echo $message; ?>
                </div> 
                <?php
            }
        }
          if (isset($daterange) && !empty($daterange)) {
        ?>    
        <h3 class="header smaller lighter blue current-websiteid" data-id="<?php echo $daterange; ?>">Website Traffics</h3>
         <?php }else{ ?>
        <h3 class="header smaller lighter blue current-websiteid" data-id="Select Date Range">Website Traffics</h3>
         <?php } ?>
        <div class="row ">

            <div class="well" style="overflow: auto;margin: 0 12px 10px;">

                <div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc">
                    <?php if (isset($daterange) && !empty($daterange)) { ?>
                    <input class="form-control get-date-range hidden" name="date-range-picker" id="date-range-picker" type="text" data-date-format="dd-mm-yyyy" value="<?php echo $daterange; ?>" />
                    <?php }else{ ?>
                    <input class="form-control get-date-range hidden" name="date-range-picker" id="date-range-picker" type="text" data-date-format="dd-mm-yyyy" />
                    <?php } ?>
                    <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                    <span></span> <b class="caret"></b>
                </div>

                <div class="pull-left">

                    <select class="form-control" id="form-field-select-1" data-id="googleapi" style="width: 300px; margin-right: 15px; margin-top: 5px;">
                        <?php if (isset($current_website_id) && $current_website_id != '') { ?>
                            <?php
                            foreach ($client_websites as $website) {
                                if ($current_website_id == $website->id) {
                                    ?>
                                    <option value="<?php echo $website->id ?>"><?php echo $website->website ?></option>
                                    <?php
                                }
                            }
                            ?>
                            <?php
                            foreach ($client_websites as $website) {
                                if ($current_website_id != $website->id) {
                                    ?>                        
                                    <option value="<?php echo $website->id ?>"><?php echo $website->website ?></option>
                                    <?php
                                }
                            }
                            ?>
                        <?php } else { ?>

                            <?php foreach ($client_websites as $website) {
                                ?>
                                <option value="<?php echo $website->id ?>"><?php echo $website->website ?></option>
                            <?php } ?>
                        <?php }
                        ?>
                    </select>

                </div>
                <?php  if (!isset($website_data) || empty($website_data)) { ?>
                <p class="pull-right" style="margin-right: 10px; color: red">Please Select Daterange For Selected Website</p>
                <?php } ?>
            </div>
        </div>  
         <a href="/googleapi/add/<?php echo $current_website_id; ?>" id="addbuttonlink"></a>
         <?php if (isset($website_data) && !empty($website_data)) { ?>
        <div class="table-header" style="min-height: 42px;">
           
            <?php if (isset($website_data['organic']) && !empty($website_data['organic'])) { ?>
            <div >Organic Search : <?php echo $website_data['organic']; ?></div>
<?php } ?>
        </div>
       
        <div class="table-responsive">
            <table id="sample-table-2" class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Page Path</th>     
                        <th>Pageviews</th>                                     
                        <th class="hidden"></th>
                        <th class="hidden"></th>
                        <th class="hidden"></th>                    
                        <th class="hidden"></th>                    
                        <th class="hidden"></th>                    
                    </tr>
                </thead>

                <tbody class="transcripttable">
                    <tr>

                        <?php
                       
                            foreach ($website_data as $google_api_data) {
//                            print_r($google_api_data);exit;
                                ?>

                                <td>
                                 <?php echo $google_api_data['path']; ?>
                                </td>
                                <td><?php echo $google_api_data['pageviews'] ?></td>
                                <td class="hidden"></td>
                                <td class="hidden"></td>
                                <td class="hidden"></td>              
                                <td class="hidden"></td>              
                                <td class="hidden"></td>              

                            </tr>
                        <?php }
                   
                     ?>              
                </tbody>
            </table>
        </div>
       <?php } ?>
    </div>
</div>
<div id="modal-table" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header no-padding">
                <div class="table-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        <span class="white">&times;</span>
                    </button>
                    Delete Website Traffic
                </div>
            </div>

            <div class="modal-body no-padding">
                <h4 style="margin: 20px 3px;">Are you sure you want to delete ?</h4>
            </div>

            <div class="modal-footer no-margin-top">

                <button class="btn btn-sm btn-danger pull-left delete_user_btn" data-dismiss="modal">
                    <i class="icon-remove"></i>
                    Yes
                </button>

                <button class="btn btn-sm btn-primary pull-left" data-dismiss="modal">
                    <i class="icon-only"></i>
                    Close
                </button>

            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal-table -->
<?php
$message = '';
$session->offsetSet('current_website_id', '');
$session->offsetSet('daterange', '');
$session->offsetSet('from', '');
$session->offsetSet('till', '');
$session->offsetSet('msg', '');
?>