 <div class="row ">

            <div class="well" style="overflow: auto; margin: 0 12px 10px; background-color: #fff; border: none; box-shadow: none;">

                <div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc">
                    <input class="form-control get-date-range hidden" name="date-range-picker" id="date-range-picker" type="text" data-date-format="dd-mm-yyyy" />
                    <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                    <span></span> <b class="caret"></b>
                </div>
                <div class="pull-right" style="margin-right: 10px; font-weight: bold; ">
                    <p style="margin: 7px 0px;">Select Date Range To Download Report</p>
                </div>
                
         </div>
 </div>
<div class="row">
    <div class="space-6" id="form-field-select-1" data-id=""></div>
            <div class="space-6"></div>
            <div class="space-6"></div>
            <div class="col-sm-2"></div>
            <div class="col-sm-9">
                <a id="addbuttonlink" href="/lead/index/<?php echo $id ?>" >   
            <span class="btn btn-app btn-sm btn-light no-hover" style="width: 222px !important; padding: 18px 0 18px !important;">
                            <div class="infobox-icon">
                                    <i class="icon-group"></i>
                            </div>

                            <div class="infobox-data">
                                    <div class="infobox-content">Leads</div>
                                    
                            </div>
            </span>
              </a>
             <a href="/googleapi/index/<?php echo $id ?>" >       
            <span class="btn btn-app btn-sm btn-yellow no-hover" style="width: 222px !important; padding: 18px 0 18px !important;">
                            <div class="infobox-icon">
                                    <i class="icon-bar-chart"></i>
                            </div>

                            <div class="infobox-data">
                                    <div class="infobox-content">Website Traffic</div>
                                    
                            </div>
            </span>
             </a>     
             <a href="/link/index/<?php echo $id ?>" >           
            <span class="btn btn-app btn-sm btn-grey no-hover" style="width: 222px !important; padding: 18px 0 18px !important;">
                            <div class="infobox-icon">
                                    <i class="icon-link"></i>
                            </div>

                            <div class="infobox-data">
                                    <div class="infobox-content">Links</div>
                                    
                            </div>
            </span>
              </a>      
            <div class="space-6"></div>
            <div class="space-6"></div>
            <div class="col-sm-1"></div>
            <a href="/transcript/index/<?php echo $id ?>" >      
            <span class="btn btn-app btn-sm btn-success no-hover" style="width: 222px !important; padding: 18px 0 18px !important;">
                            <div class="infobox-icon">
                                    <i class="icon-file"></i>
                            </div>

                            <div class="infobox-data">
                                    <div class="infobox-content">Transcripts</div>
                                    
                            </div>
            </span> 
             </a>
            <a href="/book/index/<?php echo $id ?>" >    
            <span class="btn btn-app btn-sm btn-primary no-hover" style="width: 222px !important; padding: 18px 0 18px !important;margin-left: 94px;">
                            <div class="infobox-icon">
                                    <i class="icon-book"></i>
                            </div>

                            <div class="infobox-data">
                                    <div class="infobox-content">Book Status</div>
                                    
                            </div>
            </span> 
              </a>   
           </div>     
  </div>            