<?php

use Zend\Session\Container;
use Zend\Authentication\AuthenticationService;
$session = new Container('book');
$daterange=$session->offsetGet('daterange');
$auth = new AuthenticationService();
?>
<div class="row">
    <div class="col-xs-12"> 
        <?php
//         print_r($website_data);exit;
        if (isset($message) && $message != '') {
            if ($message == "Book has been successfully Deleted.") {
                ?>
                <div class="alert alert-block alert-danger">
                    <button type="button" class="close" data-dismiss="alert">
                        <i class="icon-remove"></i>
                    </button>

                    <i class="icon-ok red"></i>
                    <?php echo $message; ?>

                </div>          
            <?php } else { ?>

                <div class="alert alert-block alert-success">
                    <button type="button" class="close" data-dismiss="alert">
                        <i class="icon-remove"></i>
                    </button>

                    <i class="icon-ok green"></i>
                    <?php echo $message; ?>
                </div> 
            <?php
            }
        }
        ?>    
        <h3 class="header smaller lighter blue current-websiteid" data-id="">Books</h3>
        
        <div class="row ">
           
            <div class="well" style="overflow: auto; margin: 0 12px 10px;">

               <div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc">
                 <input class="form-control get-date-range hidden" name="date-range-picker" id="date-range-picker" type="text" data-date-format="dd-mm-yyyy" />
                   <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                   <span></span> <b class="caret"></b>
               </div>
            </div>
             
        </div>    
        <div class="table-header" style="min-height: 42px;">
             <?php if ($auth->getIdentity()->roles_id == 3) {
                ?>

                <?php
            } else if ($auth->getIdentity()->roles_id == 2) {
                if ($applying_user_rights->crud_book == 1) {
                    ?>
                   <a href="/book/add/<?php echo $current_website_id; ?>" id="addbuttonbook" class="btn btn-primary">Add New Book</a>
            <a href="#" class="btn btn-danger pull-right multiple-delete" data-id="book">Delete Selected Books</a>
                    <?php
                } else {
                    
                }
            } else {
                ?>   
                <a href="/book/add/<?php echo $current_website_id; ?>" id="addbuttonbook" class="btn btn-primary">Add New Book</a>
            <a href="#" class="btn btn-danger pull-right multiple-delete" data-id="book">Delete Selected Books</a>
                <?php
            }
            ?>          
            
           
            <div class="pull-right">

                <select class="form-control" id="form-field-select-1" data-id="book" style="width: 300px; margin-right: 15px; margin-top: 5px;">
                    <?php if (isset($current_website_id) && $current_website_id != '') { ?>
                        <?php
                        foreach ($client_websites as $website) {
                            if ($current_website_id == $website->id) {
                                ?>
                                <option value="<?php echo $website->id ?>"><?php echo $website->website ?></option>
                            <?php }
                        }
                        ?>
                        <?php
                        foreach ($client_websites as $website) {
                            if ($current_website_id != $website->id) {
                                ?>                        
                                <option value="<?php echo $website->id ?>"><?php echo $website->website ?></option>
                            <?php }
                        }
                        ?>
                    <?php } else { ?>

                        <?php foreach ($client_websites as $website) {
                            ?>
                            <option value="<?php echo $website->id ?>"><?php echo $website->website ?></option>
                        <?php } ?>
                    <?php }
                    ?>
                </select>

            </div>
             <?php
             $num=0;
                        foreach ($website_data as $transcriptt) {                            
                            $session->offsetSet('leadobject'.$num, $transcriptt);
                            $num=$num+1;
                        }    
            ?>

            <a href="/book/exportdata/<?php echo $num-1; ?>" class="btn btn-grey pull-right" data-id="book" style="margin-right: 10px;">Export</a>

        </div>

        <div class="table-responsive">
            <table id="sample-table-2" class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="center">
                            <label>
                                <input type="checkbox" class="ace" data-id="all" />
                                <span class="lbl"></span>
                            </label>
                        </th>
                        <th>Name</th>                

                        <th class="hidden"></th>
                        <th class="hidden"></th>
                        <th class="hidden"></th>
                        <th class="hidden"></th>
                        <th class="hidden"></th>
                        <th class="hidden"></th>
                         <?php if ($auth->getIdentity()->roles_id == 3) {
                                ?>   <th class="hidden"></th> <?php
                            } else if ($auth->getIdentity()->roles_id == 2) {
                                if ($applying_user_rights->crud_book == 1) {
                                    ?>   
                                <th>Actions</th>
                                    <?php
                                } else {
                                    ?>   <th class="hidden"></th> <?php
                                }
                            } else {
                                ?>   
                            <th>Actions</th>
                            <?php
                        }
                        ?>
                    </tr>
                </thead>

                <tbody class="booktable">
                    <tr>

                        <?php
//                         print_r($website_data);
                        foreach ($website_data as $book) {                         
                            ?>
                            <td class="center">
                                <label>
                                    <input type="checkbox" class="ace" data-id="<?php echo $book->id; ?>" />
                                    <span class="lbl"></span>
                                </label>
                            </td>

                            <td>
                             <?php echo $book->name; ?>
                            </td>                      
                            <td class="hidden"></td>
                            <td class="hidden"></td>
                            <td class="hidden"></td>
                            <td class="hidden"></td>
                            <td class="hidden"></td>
                            <td class="hidden"></td>
                            <?php if ($auth->getIdentity()->roles_id == 3) {
                                ?>  <td class="hidden"></td> <?php
                            } else if ($auth->getIdentity()->roles_id == 2) {
                                if ($applying_user_rights->crud_book == 1) {
                                    ?>
                                    <td>
                                        <div class="visible-md visible-lg hidden-sm hidden-xs action-buttons">
                                    <a class="green" href="<?php echo $this->url('book', array('action' => 'edit', 'id' => $book->id)); ?>">
                                        <i class="icon-pencil bigger-130"></i>
                                    </a>
                                    <!--<a href="<?php //echo $this->url('clients', array('action' => 'dialoge', 'id' => $client->id));   ?>" class="tooltip-error" data-rel="tooltip" title="Dialoge">-->
                                    <a href="#" role="button" class="red" onclick="deleterow(<?php echo $book->id; ?>,'book');"> 
                                        <i class="icon-trash bigger-130"></i>
                                    </a>
                                </div>
                                    </td>    

                                <?php } else {
                                    ?>  <td class="hidden"></td> <?php
                                }
                            } else {
                            ?>   
                            <td>
                                <div class="visible-md visible-lg hidden-sm hidden-xs action-buttons">
                                    <a class="green" href="<?php echo $this->url('book', array('action' => 'edit', 'id' => $book->id)); ?>">
                                        <i class="icon-pencil bigger-130"></i>
                                    </a>
                                    <!--<a href="<?php //echo $this->url('clients', array('action' => 'dialoge', 'id' => $client->id));   ?>" class="tooltip-error" data-rel="tooltip" title="Dialoge">-->
                                    <a href="#" role="button" class="red" onclick="deleterow(<?php echo $book->id; ?>,'book');"> 
                                        <i class="icon-trash bigger-130"></i>
                                    </a>
                                </div>

                                <div class="visible-xs visible-sm hidden-md hidden-lg">
                                    <div class="inline position-relative">
                                        <button class="btn btn-minier btn-yellow dropdown-toggle" data-toggle="dropdown">
                                            <i class="icon-caret-down icon-only bigger-120"></i>
                                        </button>

                                        <ul class="dropdown-menu dropdown-only-icon dropdown-yellow pull-right dropdown-caret dropdown-close">

                                            <li>
                                                <a href="<?php echo $this->url('book', array('action' => 'edit', 'id' => $book->id)); ?>" class="tooltip-success" data-rel="tooltip" title="Edit">
                                                    <span class="green">
                                                        <i class="icon-edit bigger-120"></i>
                                                    </span>
                                                </a>
                                            </li>

                                            <li>
                                                <a href="<?php echo $this->url('clients', array('action' => 'delete', 'id' => $client->id)); ?>" class="tooltip-error" data-rel="tooltip" title="Delete">
                                                    <span class="red">
                                                        <i class="icon-trash bigger-120"></i>
                                                    </span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </td>
                             <?php
                              } 
                                ?>
                        </tr>
                  <?php } ?>              
                </tbody>
            </table>
        </div>
    </div>
</div>
<div id="modal-table" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header no-padding">
                <div class="table-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        <span class="white">&times;</span>
                    </button>
                    Delete Book
                </div>
            </div>

            <div class="modal-body no-padding">
                <h4 style="margin: 20px 3px;">Are you sure you want to delete ?</h4>
            </div>

            <div class="modal-footer no-margin-top">

                <button class="btn btn-sm btn-danger pull-left delete_user_btn" data-dismiss="modal">
                    <i class="icon-remove"></i>
                    Yes
                </button>

                <button class="btn btn-sm btn-primary pull-left" data-dismiss="modal">
                    <i class="icon-only"></i>
                    Close
                </button>

            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal-table -->
<?php
$message = '';
$session->offsetSet('current_website_id', '');
$session->offsetSet('from', '');
$session->offsetSet('till', '');
$session->offsetSet('msg', '');
?>

